# Generated by Django 2.2 on 2020-11-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_html_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='html_message',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
    ]
