# Generated by Django 2.2 on 2020-11-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201106_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_post.jpg', upload_to='blog/'),
        ),
    ]
