# Generated by Django 2.2 on 2020-11-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201125_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='active',
            new_name='is_active',
        ),
    ]
