# Generated by Django 2.2 on 2020-11-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='html_message',
        ),
    ]
