# Generated by Django 2.2 on 2020-11-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='author_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
